4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:

1. Initialize an empty array with size 2X2.

In [2]:
#University id:2431328
#Student Name:Ugesh KC

import numpy as np
array_2x2 = np.zeros((2, 2))
print(array_2x2)



[[0. 0.]
 [0. 0.]]


2. Initialize an all one array with size 4X2.

In [9]:
import numpy as np

ones_array = np.ones((4, 2))
print(ones_array)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [4]:
fill_array = np.full((3, 3), 69)
print(fill_array)


[[69 69 69]
 [69 69 69]
 [69 69 69]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [7]:
reference_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(reference_array)
print(zeros_like_array)


[[0 0]
 [0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}


In [6]:
reference_array = np.array([[1, 2], [3, 4]])
ones_like_array = np.ones_like(reference_array)
print(ones_like_array)


[[1 1]
 [1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [8]:
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print(numpy_array)


[1 2 3 4]


4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.


In [11]:
range_array = np.arange(10, 50)
print(range_array)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [12]:
reshaped_array = np.arange(9).reshape(3, 3)
print(reshaped_array)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}


In [13]:
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}


In [14]:
random_array = np.random.random(30)
mean_value = random_array.mean()
print(mean_value)


0.536202924900463


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [15]:
random_matrix = np.random.random((10, 10))
min_value = random_matrix.min()
max_value = random_matrix.max()
print(min_value, max_value)


0.005066924477104329 0.9996948238148546


6. Create a zero array of size 10 and replace 5th element with 1.


In [16]:
zero_array = np.zeros(10)
zero_array[4] = 1
print(zero_array)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].


In [17]:
arr = [1, 2, 0, 0, 4, 0]
reversed_array = arr[::-1]
print(reversed_array)


[0, 4, 0, 0, 2, 1]



8. Create a 2d array with 1 on border and 0 inside.


In [18]:
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print(border_array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]



9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [19]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [25]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
add_result = x + y
print("add result =",add_result)
subtract_result = x - y
print("subtract result =",subtract_result)
multiply_result = x * 2
print("multiply result =",multiply_result)
square_result = x ** 2
print("square result =",square_result)
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("dot product of vw = ",dot_vw,"dot product of xv= ",dot_xv,"dot product of xy", dot_xy)
concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_column = np.vstack((v, w))
print("Concatenate x(and)y along row we get:",concat_xy_row)
print("Concatenate v(and)w along column we get:",concat_vw_column)
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    print(e)




add result = [[ 6  8]
 [10 13]]
subtract result = [[-4 -4]
 [-4 -3]]
multiply result = [[ 2  4]
 [ 6 10]]
square result = [[ 1  4]
 [ 9 25]]
dot product of vw =  219 dot product of xv=  [29 77] dot product of xy [[19 22]
 [50 58]]
Concatenate x(and)y along row we get: [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v(and)w along column we get: [[ 9 10]
 [11 12]]
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

In [32]:
import numpy as np


A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)
A_A_inv = np.dot(A, A_inv)
print("A * A⁻¹ =\n", A_A_inv)

AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB =\n", AB)
print("BA =\n", BA)
print("AB ≠ BA is not ",  np.allclose(AB, BA))

AB_T = np.transpose(AB)
BT_AT = np.dot(B.T, A.T)
print("(AB)ᵀ =\n", AB_T)
print("BᵀAᵀ =\n", BT_AT)
print("(AB)ᵀ = BᵀAᵀ is", np.allclose(AB_T, BT_AT))


A * A⁻¹ =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
AB ≠ BA is not  False
(AB)ᵀ =
 [[23 51]
 [13 29]]
BᵀAᵀ =
 [[23 51]
 [13 29]]
(AB)ᵀ = BᵀAᵀ is True


Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [30]:
import numpy as np
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print("Solution:")
print("x =", X[0])
print("y =", X[1])
print("z =", X[2])

Solution:
x = 2.0
y = 1.0
z = -2.0


• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [31]:
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])
X = np.linalg.solve(A, B)
print("Solution using np.linalg.solve:")
print("x =", X[0])
print("y =", X[1])
print("z =", X[2])

Solution using np.linalg.solve:
x = 2.0
y = 1.0000000000000002
z = -2.0
